### PR TITLE
Pin graphql core <3.1

### PR DESCRIPTION
**Pull request by chewselene**
3.1 contains a breaking change.

### CODE REVIEW

**Comment by bojanserafimov** [comment]
Should also update setup.py.

Sad to see the semver https://semver.org/ principles broken.

**Comment by obi1kenobi** [comment]
3.1 is the Python equivalent of the Javascript v15 library.
3.0 is the Python equivalent of the Javascript v14 library.

The Javascript library seems to be following semver. I'm not sure what we were using is internal, so it may or may not be on us. We should maybe bring this up with the GraphQL-core maintainers, just to understand what our expectations should be around version bumps. In the meantime, I suggest we pin to minor versions instead of majors.

**Comment by obi1kenobi** [comment]
@bojanserafimov can you take a look at the `query_parameterizer.py` lint issues? I think the version bump allowed mypy to do some deeper analysis and it's now unhappy.

**Comment by obi1kenobi** [comment]
The `helpers.py` mypy issue seems like it might be an instance of https://github.com/python/mypy/issues/5374 so let's `# type: ignore` it.

**Comment by bojanserafimov** [comment]
Sure. I'll send a diff for that file soon.

**Comment by bojanserafimov** [comment]
https://github.com/kensho-technologies/graphql-compiler/pull/794

**Pull request merged**
