### PR TITLE
Python 3 compatibility: basestring, unicode(), xrange()

### PR DESCRIPTION
**Pull request by cclauss**
Fixes for 30 flake8 errors on Python 3...

flake8 testing of https://github.com/kensho-technologies/graphql-compiler on Python 3.6.2

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__

```
./graphql_compiler/debugging_utils.py:19:18: F821 undefined name 'xrange'
        for i in xrange(0, len(too_many_parts) - 1, 2)
                 ^

./graphql_compiler/debugging_utils.py:24:14: F821 undefined name 'xrange'
    for i in xrange(1, len(parts)):
             ^

./graphql_compiler/debugging_utils.py:87:26: F821 undefined name 'xrange'
                for i in xrange(1, len(separate_keywords) - 1, 2):
                         ^

./graphql_compiler/compiler/blocks.py:55:35: F821 undefined name 'basestring'
                all(isinstance(x, basestring) for x in self.start_class)):
                                  ^

./graphql_compiler/compiler/blocks.py:98:35: F821 undefined name 'basestring'
                all(isinstance(x, basestring) for x in self.target_class)):
                                  ^

./graphql_compiler/compiler/blocks.py:256:43: F821 undefined name 'basestring'
        if not isinstance(self.direction, basestring):
                                          ^

./graphql_compiler/compiler/blocks.py:320:43: F821 undefined name 'basestring'
        if not isinstance(self.direction, basestring):
                                          ^

./graphql_compiler/compiler/blocks.py:347:22: F821 undefined name 'xrange'
            for i in xrange(self.depth + 1)
                     ^

./graphql_compiler/compiler/expressions.py:78:35: F821 undefined name 'basestring'
        if isinstance(self.value, basestring):
                                  ^

./graphql_compiler/compiler/expressions.py:102:37: F821 undefined name 'basestring'
        elif isinstance(self.value, basestring):
                                    ^

./graphql_compiler/compiler/expressions.py:107:36: F821 undefined name 'basestring'
            elif all(isinstance(x, basestring) for x in self.value):
                                   ^

./graphql_compiler/compiler/expressions.py:182:41: F821 undefined name 'unicode'
        match_variable_name = '{%s}' % (unicode(variable_with_no_dollar_sign),)
                                        ^

./graphql_compiler/compiler/expressions.py:206:20: F821 undefined name 'unicode'
            return unicode(self.variable_name)
                   ^

./graphql_compiler/compiler/expressions.py:237:16: F821 undefined name 'unicode'
        return unicode(self.field_name)
               ^

./graphql_compiler/compiler/expressions.py:619:42: F821 undefined name 'unicode'
        if not isinstance(self.operator, unicode):
                                         ^

./graphql_compiler/compiler/helpers.py:10:36: F821 undefined name 'unicode'
VARIABLE_ALLOWED_CHARS = frozenset(unicode(string.ascii_letters + string.digits + '_'))
                                   ^

./graphql_compiler/compiler/helpers.py:60:30: F821 undefined name 'basestring'
    if not isinstance(value, basestring):
                             ^

./graphql_compiler/compiler/helpers.py:62:12: F821 undefined name 'unicode'
    return unicode(value)
           ^

./graphql_compiler/compiler/helpers.py:100:30: F821 undefined name 'basestring'
    if not isinstance(value, basestring):
                             ^

./graphql_compiler/compiler/helpers.py:158:44: F821 undefined name 'basestring'
        if field and not isinstance(field, basestring):
                                           ^

./graphql_compiler/compiler/helpers.py:185:34: F821 undefined name 'basestring'
        if not isinstance(child, basestring):
                                 ^

./graphql_compiler/compiler/helpers.py:199:60: F821 undefined name 'unicode'
        mark_name = u'__'.join(self.query_path) + u'___' + unicode(self.visit_counter)
                                                           ^

./graphql_compiler/query_formatting/gremlin_formatting.py:19:30: F821 undefined name 'basestring'
    if not isinstance(value, basestring):
                             ^

./graphql_compiler/query_formatting/gremlin_formatting.py:89:43: F821 undefined name 'basestring'
        if not isinstance(argument_value, basestring):
                                          ^

./graphql_compiler/query_formatting/gremlin_formatting.py:90:30: F821 undefined name 'unicode'
            argument_value = unicode(argument_value)
                             ^

./graphql_compiler/query_formatting/match_formatting.py:18:30: F821 undefined name 'basestring'
    if not isinstance(value, basestring):
                             ^

./graphql_compiler/query_formatting/match_formatting.py:75:43: F821 undefined name 'basestring'
        if not isinstance(argument_value, basestring):
                                          ^

./graphql_compiler/query_formatting/match_formatting.py:76:30: F821 undefined name 'unicode'
            argument_value = unicode(argument_value)
                             ^

./graphql_compiler/tests/test_helpers.py:37:14: F821 undefined name 'xrange'
    for i in xrange(len(expected_blocks)):
             ^

./graphql_compiler/tests/test_ir_generation_errors.py:441:48: F821 undefined name 'xrange'
            args = (variable_names[i] for i in xrange(num_args))
                                               ^
```

### CODE REVIEW

**Comment by obi1kenobi** [comment]
Hey @cclauss, thank you for the PR and for helping make this project Python 3 compatible!

To avoid duplicating the `try-except-NameError` block at the top of many files, what do you think about having a single top-level `compat.py` file that has all the Python version compatibility things like that, and then import it wherever they are necessary?

Otherwise, looks good to me. Reminder to please sign the CLA so I can merge this when it's ready -- the link is the `Details` part of the `clahub` merge check.

**Comment by ColCarroll** [comment]
Might be more maintainable to use

```
from six.moves import xrange
from six import string_types as basestring
```

instead of special casing!

**Comment by obi1kenobi** [comment]
@ColCarroll I assume there's also something in `six` that works around the `unicode` vs `str` problems too? I'm open to adding `six` as a dependency if it helps make this easier.

**Comment by ColCarroll** [comment]
Ah yeah, looks like `from six import text_type as unicode`.  I like the idea of putting these in `compat.py` in case it needs to change, or there is more logic to be added later.  `flask` actually calls it `_compat` so it does not make the top level namespace any busier.  Good comments there:

https://github.com/pallets/flask/blob/master/flask/_compat.py

**Comment by obi1kenobi** [comment]
From flask:
```
Some py2/py3 compatibility support based on a stripped down
version of six so we don't have to depend on a specific version of it.
```
Since we're only using like ~3 things, I think we can afford to write our own tiny `compat.py` file instead of depending on `six`. Thoughts?

**Comment by ColCarroll** [comment]
Yah -- seems like it would be like ~8 lines.  What are your thoughts on using `text_type` and `string_types` instead of `unicode` and `basestring`?

**Comment by obi1kenobi** [comment]
I think that's fine and probably preferable -- it'll also silence pylint. I'm also willing to help if @cclauss wants some help.

**Comment by cclauss** [comment]
Closed in favor of #17

**Pull request closed without merging**
